<?php

namespace quizzBundle\Repository;

/**
 * QuestrepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestrepRepository extends \Doctrine\ORM\EntityRepository
{

}
